### ISSUE TITLE
Package einenlum/linguee-api has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version  

### ISSUE THREAD

**Issue by kurt-krueckeberg** [Einenlum/linguee-api#1]
Thanks for you Linguee-API PHP library. When I installed it using composer

    composer require einelum/linguee-api

I got 

    Package einenlum/linguee-api has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version  

Which PHP extensions are needed to use your Linguee API PHP library?

**Comment by einenlum** [comment]
Hi @kurt-krueckeberg,

Thanks for your issue. What is your PHP version? This package is old and not PHP 8 compatible for now but I will try to upgrade it soon.

**Comment by kurt-krueckeberg** [comment]
Thanks for the prompt reply. I am using PHP 8.0.8.
I may simply use Goutte instead and scrape Linguee..

regards,
Kurt

**Comment by einenlum** [comment]
I updated the library to version 0.1.0. It should now support PHP 7.4 up to 8.1.
Can you check if everything works for you?

**Comment by kurt-krueckeberg** [comment]
Yes, it seems to be working. I was able to use composer to install it, and the example code in the README ran successfully. Thanks a lot!
